### PR TITLE
Custom slugify

### PR DESCRIPTION
**Pull request by gimenete**
A custom `slug` function that works with https://github.com/xataio/xata/blob/4397604f6b9b3a33551ebfb25d6cf5b27ec3e4dd/internal/xvalidator/xvalidator.go#L17

We'll probably need to do the same in the frontend.
An alternative would've been that the slug is optional and the backend generates a valid one if not provided.

Closes https://github.com/xataio/client-ts/issues/468

### CODE REVIEW

**Review by SferaDev — APPROVED** [review]
LGTM

I think this is a helpful util. What do you think of having it and exporting from the SDK and using it in the CLI and potentially the frontend without repeating the implementation.

Also, debatable but what if instead of doing anything on the CLI, we added this logic to the API call in the SDK. If slug is provided it must be in slug format, if slug is not provided it is auto computed from the name.

**Comment by gimenete** [comment]
@SferaDev those are great ideas. The only thing is that this implementation depends on a third party package. Maybe we can drop that dependency and just do a fully custom implementation with a regex, and then we can move it to the SDK without adding a dependency to it. WDYT?

**Comment by SferaDev** [comment]
Sounds good to me!

Shouldn't be too hard to implement and provides a helpful utility to the SDK (that we and users will likely need)

**Comment by gimenete** [comment]
@SferaDev cool. I'm going to merge this to close the issue it addresses and I've opened https://github.com/xataio/client-ts/issues/473

**Pull request merged**
