### PR TITLE
Add `xata.*` columns to `SelectableColumn`

### PR DESCRIPTION
**Pull request by andrew-farries**

### CODE REVIEW

**Comment by SferaDev** [comment]
Not sure about adding it to selectable columns as they are completely virtual, probably they should be added to the `metadata` similar to how `version` or the other properties coming from search can be retrieved

**Comment by andrew-farries** [comment]
> Not sure about adding it to selectable columns as they are completely virtual, probably they should be added to the `metadata` similar to how `version` or the other properties coming from search can be retrieved

Thanks. I haven't worked with the Typescript SDK before, so this draft PR is just me playing around with how we could add this 😄

**Comment by SferaDev** [comment]
If you want we can pair and implement it together. There're 2 things you need to make sure here:

1. Types
2. Actual response matches the types

There's a way to increase the types coming from the metadata of a XataRecord via it's generic type.

**Comment by andrew-farries** [comment]
Closing in favour of https://github.com/xataio/client-ts/pull/1009

**Pull request closed without merging**
