### PR TITLE
Generate typedefs from dts files

### PR DESCRIPTION
**Pull request by SferaDev**
Emit declaration files and import type defs from them

Closes: #143

### CODE REVIEW

**Review by gimenete — APPROVED** [review]
This works great!

image

I'm wondering if we could improve this (not necessarely in this PR):

image

**Comment by SferaDev** [comment]
Werid @gimenete 

To me even inside a ``then`` it types it properly

Screenshot 2022-05-05 at 12 49 27
Screenshot 2022-05-05 at 12 49 34

**Comment by gimenete** [comment]
@SferaDev weird, this is a video with more information:

https://user-images.githubusercontent.com/50486/166913318-664c1df3-9491-4b86-97e2-9c45e4806cc8.mp4

If you think I'm doing something wrong, let me know 😅

**Comment by SferaDev** [comment]
Something is up with VSCode then, it works on my machine. Video doing the same as you:

https://user-images.githubusercontent.com/2181866/166917398-50de72eb-6d39-4770-ad9d-8e752a2455f6.mp4

I'm in Insiders build, with TS 4.7 dev. But not sure it should make a difference...

**Comment by gimenete** [comment]
@SferaDev ok, no worries. I'll try to figure it out 😅

**Pull request merged**
